# Generated by Django 4.2.10 on 2024-02-16 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Homepage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("photo", models.FileField(blank=True, upload_to="project_images/")),
                ("email", models.EmailField(max_length=254)),
                ("linkedin", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                (
                    "Homepage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.homepage"
                    ),
                ),
            ],
        ),
    ]
