# Generated by Django 4.2.10 on 2024-03-01 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="photo",
        ),
    ]
