services:
  api:
    build: ./backend
    ports:
      - "8080:8080"
    command: bash -c "python manage.py runserver 0.0.0.0:8080"

  web:
    container_name: app-prod
    image: app-prod
    build:
      context: .
      target: production
