# Generated by Django 5.0.1 on 2024-01-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.TextField(
                choices=[
                    ("WEDDING", "Wedding"),
                    ("INTERIOR_DECORATION", "Interior Decoration"),
                    ("FLOWERS", "Flower Arrangments"),
                    ("HANDCRAFT", "Handcraft"),
                ],
                default="INTERIOR_DECORATION",
            ),
        ),
    ]
